name: CI
on:
  push:
    branches: [default]
  pull_request:
permissions:
  contents: read
jobs:
  ci:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-ci.yml@65e1d30043e2fec1a49ebfba36d771d2acce8e2c # main
    with:
      node-versions: '[22, 24]'
      has-build: false
