name: commitlint
on:
  pull_request:
permissions:
  contents: read
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@65e1d30043e2fec1a49ebfba36d771d2acce8e2c # main
