name: release-cut
on:
  schedule:
    - cron: '0 6 1 * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  cut:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-cut.yml@65e1d30043e2fec1a49ebfba36d771d2acce8e2c # main
    secrets: inherit
